### ISSUE TITLE
Need Class Props for step List Item and Anchor

### ISSUE THREAD

**Issue by ggedde** [BinarCode/vue-form-wizard#235]
I noticed there is a Prop on the wizard for "stepsClasses" (Which is not in your Documentation), but I also need one for the `<li>` and the `<a>` when using tabs.  

I would suggest the following:
stepsItemClasses
stepsLinkClasses
or something to that effect.

Thanks

**Comment by cristijora** [comment]
Hi @ggedde You could always use the explicit `step` slots to customize everything based on your needs.
Here is an example https://jsfiddle.net/bt5dhqtf/3638/
More details in docs http://vuejs.creative-tim.com/vue-form-wizard/#/?id=step-slot
If this is not enough, feel free to open a PR and I will be glad to review it.

**Comment by ggedde** [comment]
Thanks, that is what I am doing, but would prefer not to have to customize the whole slot.
I mainly need this feature to apply bootstrap class names to them.
