### ISSUE TITLE
Hide tabs

### ISSUE THREAD

**Issue by paulvonber** [BinarCode/vue-form-wizard#260]
Is there any option to hide the tabs? I mean in some cases I need many steps, but I don't want to show the tabs to indicate how many steps exists.

Thanks!

**Comment by danawesome** [comment]
Try this:
`<tab-content
    v-if="datavar"
>`
Assumes datavar is truthy

`<tab-content
    v-if="datavar==='myValue'"
>`
For what ever reason v-show doesn't seem to work, needs to be v-if

**Comment by jonalxh** [comment]
I've added the following CSS in my .vue file: 

```
/deep/ .vue-form-wizard {
	.wizard-header {
		display: none;
	}
	ul.wizard-nav-pills,
	.wizard-progress-with-circle {
		display: none !important;
	}
}
```

I hope it help.
