### ISSUE TITLE
How to add spinning loader on a finish button?

### ISSUE THREAD

**Issue by bernarddoci** [BinarCode/vue-form-wizard#265]
After going through all the steps at the end I have to submit all the forms
with finish button. So how can I add loading spinner on a finish button.

**Comment by eLiXee** [comment]
You can call a function on complete 
 <form-wizard @on-complete="runFunction"> you can handle what you want within that function like showing a loading spinner.

**Comment by yogithesymbian** [comment]
did you solve it ? @bernarddoci

**Comment by yogithesymbian** [comment]
currently i only can `this.$refs.wizard.hideButtons = true` hide the button to prevent user to double click. but i look there is `fillButtonStylle` on slots .

**Comment by yogithesymbian** [comment]
> You can call a function on complete <form-wizard @on-complete="runFunction"> you can handle what you want within that function like showing a loading spinner.

did you know the scope of submit button ? we need for example , these documentation is not completed
```
Since [0.6.4](https://github.com/cristijora/vue-form-wizard/releases/tag/v0.6.4), button slots can be also used as scoped slots and have the following methods/properties exposed

nextTab // will go to the next tab/step when called
prevTab //will got to the prev tab/step when called
activeTabIndex // current active tab index
isLastStep // boolean to tell whether it's the last step or not
fillButtonStyle // object with styles for wizard-buttons (contains background and color passed through wizard props)
These properties apply to the following slots:

prev - Previous button content (no need to worry about handling the button functionality)
next - Next button content
finish - Finish button content
custom-buttons-left - Appears on right of "Back" button
custom-buttons-right - Appears on the left of "Next/Finish" button
```

**Comment by yogithesymbian** [comment]
> > You can call a function on complete <form-wizard @on-complete="runFunction"> you can handle what you want within that function like showing a loading spinner.
> 
> did you know the scope of submit button ? we need for example , these documentation is not completed
> 
> ```
> Since [0.6.4](https://github.com/cristijora/vue-form-wizard/releases/tag/v0.6.4), button slots can be also used as scoped slots and have the following methods/properties exposed
> 
> nextTab // will go to the next tab/step when called
> prevTab //will got to the prev tab/step when called
> activeTabIndex // current active tab index
> isLastStep // boolean to tell whether it's the last step or not
> fillButtonStyle // object with styles for wizard-buttons (contains background and color passed through wizard props)
> These properties apply to the following slots:
> 
> prev - Previous button content (no need to worry about handling the button functionality)
> next - Next button content
> finish - Finish button content
> custom-buttons-left - Appears on right of "Back" button
> custom-buttons-right - Appears on the left of "Next/Finish" button
> ```

found here https://jsfiddle.net/bt5dhqtf/717/
