### ISSUE TITLE
Question: Add next/previous buttons outside of the form-wizard

### ISSUE THREAD

**Issue by Kalifax** [BinarCode/vue-form-wizard#269]
![bilde](https://user-images.githubusercontent.com/706874/47559397-ab859880-d915-11e8-8682-4bee4755c17c.png)

A use case we have is that all contextual state should be placed at the top of the page, like the image above. Any idea on how to control next/previous buttons outside of the `<form-wizard`. How do one access methods `nextTab()` and `previousTab()` when not inside the container of `<form-wizard`?

**Comment by nsh-core** [comment]
you can add a ref to the form-wizard element then access anything in the component pragmatically

`<form-wizard ref="myWizard">`

`this.ref['myWizard'].nextTab();`

**Comment by piggylabs** [comment]
`this.$refs.myWizard.nextTab();`
