### ISSUE TITLE
Progress bar not completing properly

### ISSUE THREAD

**Issue by arghyac35** [BinarCode/vue-form-wizard#297]
![image](https://user-images.githubusercontent.com/27964664/56727179-c8d4db80-676d-11e9-83ab-802503213bc4.png)
The progress bar is being like this, any solution will be grateful. Thank you.

**Comment by arghyac35** [comment]
Okay got an around and fixed it.

**Comment by dohahelmy** [comment]
How did you fixed that? please explain as I need to change how the width is changing on steps.
