### ISSUE TITLE
How can i remove steps navigation bar without css "display:none"

### ISSUE THREAD

**Issue by fatihsinanyaman** [BinarCode/vue-form-wizard#301]
![Screen Shot 2019-06-13 at 17 50 35](https://user-images.githubusercontent.com/6079978/59442958-dddff980-8e03-11e9-84bf-24f83abc045b.png)

i want to remove this steps navigation bar but no there any props about that

**Comment by icrotz** [comment]
You can use my fork https://github.com/KOJI-SAS/vue-form-wizard
