### ISSUE TITLE
before-change work on npm package now?

### ISSUE THREAD

**Issue by essramos** [BinarCode/vue-form-wizard#318]
Also if its not, how to register components using github direct links? 

Thanks!

**Comment by Braincoke** [comment]
Not sure what the question is about. But for anyone wondering, before-change works properly. Just make sure you return `true` in the function called.

E.g
```vue
<tab-content
  :before-change="doThisBefore"
  title="First Step">
              ...
</tab-content>
```

And 
```js
methods: {
  doThisBefore() {
    console.log('Hello');
    return true;
  }
}
```
