### ISSUE TITLE
 Property or method "foo" is not defined on the instance but referenced during rende

### ISSUE THREAD

**Issue by essramos** [BinarCode/vue-form-wizard#319]
Hello, 

I am having this bug on the form wizard. Any idea what is happening? 

Here are the logs on the console. 

![image](https://user-images.githubusercontent.com/8519223/65395763-191f8c00-dd54-11e9-83b0-411941084e9a.png)

**Comment by BRafols** [comment]
No code, no way to solve it.

Probably has nothing to do with the library
