### ISSUE TITLE
disabled button next previous finish

### ISSUE THREAD

**Issue by SnoxiK** [BinarCode/vue-form-wizard#331]
Hello I would need help to know how to disable the buttons during an axios request thank you

**Comment by topegret** [comment]
not an elegant way but what about css display:none  
`.wizard-btn {
      display:none  ! important 
}`

**Comment by Kalifax** [comment]
You need to use a custom footer. In there, you :disable the buttons when content is loading.

@cristijora It would be nice to have this as an exposed property for easier usage and less custom markup since you already can customize next and previous button texts.

I.e:

```
<form-wizard
      title="Register"
      subtitle="Welcome to user registration"
      nextButtonText="Next"
      :nextButtonDisabled="loading"
      :backButtonDisabled="loading"
>
.....
```

**Comment by SnoxiK** [comment]
thank's :)
