### ISSUE TITLE
Not working semantic ui on vue-router

### ISSUE THREAD

**Issue by M3hdi-Rostami** [BinarCode/vue-form-wizard#335]
Hi guys ... i'm using vuejs in a laurel project .. and i used semantic ui html for frantis in vue (not semantic-ui-vue !!!) so i had no problem here And it's all okay! I also use a vue-router to handle different sections or pages ... and here's the problem! That is, when I display a page with a vue-router, the semantic elements no longer work (their styles are just not actionable !!!) but when I refresh the page it works !!! What do you think the problem might be ??? Thankful

**Comment by BRafols** [comment]
Ehm, don't really know where to start, probably has nothing to do with this repo.
